"who is father of computer"=[
        "charles babage",
        "denis ritchie",
        "james gosling",
        "dale carnage"
       ]   
    "what is python extension"=[
        ".py",
        ".p",
        ".python",
        ".pip"
        ]